apiVersion: monitor.azure.com/v1
kind: Instrumentation
metadata:
  name: default
spec:
  settings:
    autoInstrumentationPlatforms:
      - NodeJs
  destination: 
    applicationInsightsConnectionString: "" # Update with Azure App Insights connection string